version: '3'
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"

    depends_on:
      - frontend
      - api
      - reader
  
  reader:
    build: ./reader_service
    volumes: 
      - /srv/books:/srv/books
      - ./reader_service/public:/usr/share/nginx/html/reader
  
  frontend:
    build: ./frontend_service/

  api:
    build: ./api_service/

  books_updater:
    build: ./books_updater_service/
    volumes:
    - /srv/books:/app/res
    - ./books_updater_service/upload:/app/upload

  mongo:
    build: ./mongo_service/
    restart: always
    volumes:
    - ./mongo_service/mongodb_data:/data/db

    ports:
      - "27777:27017"

    environment:
      MONGO_INITDB_DATABASE: books

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: test
