version: '3'
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"

    depends_on:
      - frontend
      - api
      - reader
  
  reader:
    build: ./reader_service
    volumes: 
      - /srv/books:/srv/books
      - ./reader_service/public:/usr/share/nginx/html/reader
  
  frontend:
    build: ./frontend_service/

  api:
    build: ./api_service/
    environment: 
      MONGO_URI: "mongodb://root:test@mongo:27017/books?authSource=books"
    volumes: 
      - ./api_service:/app
    
    depends_on:
      - mongo

  books_updater:
    build: ./books_updater_service/
    volumes:
    - /srv/books:/app/res
    - /srv/upload:/app/upload
    
    environment: 
      MONGO_URI: "mongodb://root:test@mongo:27017/books?authSource=books"
    
    depends_on:
        - mongo

  mongo:
    build: ./mongo_service/
    restart: always
    volumes:
    - /srv/mongodb_data:/data/db

    ports:
      - "27777:27017"

    environment:
      MONGO_INITDB_DATABASE: books
