version: '3'
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"

    depends_on:
      - frontend
      - api

  frontend:
    build: ./frontend_service/

  api:
    build: ./api_service/

  books_updater:
    build: ./books_updater_service/
    volumes:
    - ./books_updater_service/res:/app/res
    - ./books_updater_service/upload:/app/upload

  mongo:
    image: mongo
    restart: always
    volumes:
    - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test



